# Generated by Django 4.2.2 on 2023-06-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_file_title_alter_gltffile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gltffile',
            name='url',
            field=models.FileField(upload_to='gltf/'),
        ),
    ]
