# Generated by Django 4.1.7 on 2023-03-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_react_delete_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="react",
            name="csv",
            field=models.FileField(blank=True, null=True, upload_to="csv/"),
        ),
    ]
