# Generated by Django 4.2.2 on 2023-06-26 23:25

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLTFFile',
            fields=[
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.file')),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='titulo', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.FileField(default='titulo', editable=False, upload_to=api.models.upload_to),
            preserve_default=False,
        ),
    ]
