# Generated by Django 4.1.7 on 2023-03-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="file",
            new_name="csv",
        ),
    ]
