# Generated by Django 4.1.7 on 2023-03-20 20:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_file_file_csv"),
    ]

    operations = [
        migrations.DeleteModel(
            name="React",
        ),
        migrations.RemoveField(
            model_name="file",
            name="csv",
        ),
        migrations.AddField(
            model_name="file",
            name="csv_url",
            field=models.FileField(blank=True, upload_to=api.models.upload_to),
        ),
        migrations.AddField(
            model_name="file",
            name="title",
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
