# Generated by Django 4.2.2 on 2023-06-27 00:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gltffile_delete_react_remove_file_file_file_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gltffile',
            name='url',
            field=models.FileField(blank=True, upload_to=api.models.upload_to),
        ),
    ]
