# Generated by Django 4.1.5 on 2023-03-28 20:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_delete_react_remove_file_csv_file_csv_url_file_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gltf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("url", models.FileField(blank=True, upload_to=api.models.upload_to)),
            ],
        ),
        migrations.RenameField(
            model_name="file",
            old_name="csv_url",
            new_name="url",
        ),
    ]
