# Generated by Django 4.1.7 on 2023-03-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_gltf_rename_csv_url_file_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Gltf",
        ),
        migrations.RenameField(
            model_name="file",
            old_name="url",
            new_name="csv_url",
        ),
    ]
