# Generated by Django 4.1.7 on 2023-03-28 22:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_gltf_rename_csv_url_file_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="GLTFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "gltf_file",
                    models.FileField(blank=True, upload_to=api.models.upload_to),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Gltf",
        ),
    ]
