# Generated by Django 4.1.7 on 2023-03-28 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_gltffile_file_alter_gltffile_gltf_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gltffile",
            name="id",
        ),
        migrations.RemoveField(
            model_name="gltffile",
            name="name",
        ),
        migrations.AlterField(
            model_name="gltffile",
            name="file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="api.file",
            ),
        ),
    ]
