# Generated by Django 4.1.7 on 2023-03-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_gltffile_id_remove_gltffile_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gltffile",
            name="gltf_file",
        ),
        migrations.AlterField(
            model_name="file",
            name="url",
            field=models.FileField(
                blank=True, upload_to="csv/<django.db.models.fields.CharField>"
            ),
        ),
    ]
