# Generated by Django 4.1.7 on 2023-03-29 00:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_gltffile_gltf_file_alter_file_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="url",
            field=models.FileField(blank=True, upload_to=api.models.upload_to),
        ),
    ]
