# Generated by Django 4.1.7 on 2023-03-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_gltffile_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gltffile",
            name="url",
        ),
    ]
