# Generated by Django 4.2 on 2023-05-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_remove_gltffile_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="type",
            field=models.CharField(
                choices=[("csv", "CSV")], default="csv", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="gltffile",
            name="type",
            field=models.CharField(
                choices=[("gltf", "GLTF")], default="gltf", max_length=10
            ),
        ),
    ]
