# Generated by Django 4.2 on 2023-05-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_gltffile_dict"),
    ]

    operations = [
        migrations.AddField(
            model_name="gltffile",
            name="exists",
            field=models.BooleanField(default=False),
        ),
    ]
