# Generated by Django 4.2 on 2023-05-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_gltffile_exists"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="type",
        ),
        migrations.RemoveField(
            model_name="gltffile",
            name="dict",
        ),
        migrations.RemoveField(
            model_name="gltffile",
            name="exists",
        ),
        migrations.RemoveField(
            model_name="gltffile",
            name="type",
        ),
    ]
