# Generated by Django 4.2 on 2023-05-30 22:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_remove_file_type_remove_gltffile_dict_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="url",
            field=models.FileField(editable=False, upload_to=api.models.upload_to),
        ),
    ]
