version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx//conf.d/default.conf
      - ./static:/static:delegated
    restart: always

  web:
    image: 504665151496.dkr.ecr.us-east-1.amazonaws.com/liho:latest
    container_name: web
    command: gunicorn liho.wsgi:application --bind 0.0.0.0:8000 -w 2
    volumes:
      - .:/app:delegated
