services:
  - name: nginx
    type: web
    env:
      DOCKER_IMAGE: nginx:latest
    ports:
      - 80

  - name: web
    env: python
    buildCommand: poetry install --no-dev && python manage.py collectstatic --noinput
    startCommand: gunicorn liho.wsgi:application --bind 0.0.0.0:8000 -w 2
    envVars:
      - key: SECRET_KEY
        value: "{{ env.SECRET_KEY | default('django-insecure-nr7u^8r&)e%v_%7sclnb$-kfhv17ra*l59_wt7lk4%bp#9f9qf') }}"
      - key: DATABASE_URL
        value: "{{ env.DATABASE_URL | default('postgres://liho_postgresql_exj0_user:E45WCqjiIuTl1mJKtCDCW8DWAqx7IyZk@dpg-cid1u1lph6esg7fj1gpg-a.oregon-postgres.render.com/liho_postgresql_exj0') }}"
    ports:
      
      - 8000
    healthCheckPath: /health-check
    healthCheckPort: 8000
    healthCheckTimeoutSeconds: 5
    healthCheckIntervalSeconds: 10
    healthCheckMaxRetries: 3
    healthCheckStartPeriodSeconds: 10
    healthCheckGracePeriodSeconds: 10
    healthCheckFailureThreshold: 3
    healthCheckSuccessThreshold: 1
    healthCheckType: http
    healthCheckHttpMethod: GET
    healthCheckHttpPath: /health-check
    healthCheckHttpProtocol: HTTP
    healthCheckHttpPort: 8000
    healthCheckHttpStatusCode: 200