services:
  - name: nginx
    type: web
    env:
      DOCKER_IMAGE: nginx:latest
    ports:
      - 80

    ports:
      - 8000
    startCommand: gunicorn liho.wsgi:application --bind 0.0.0.0:8000 -w 2
